### ISSUE TITLE
Successful transaction returns 'Not found'

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/cashscript#11]
Randomly transactions don't return a txid but they properly spend the funds.

The code looks like this:

```ts
    const tx: TxnDetailsResult = await instance.functions
      .spend(1, 9)
      .send(addy, contractBalance - 2000)
    console.log("transaction details:", tx)
```

Returns `{ error: 'Not found' }` but the transaction correctly went through.

**Comment by rkalis** [comment]
After sending the transaction to the network, the CashScript SDK waited for 2 seconds and then retrieved and returned the transaction details. However, sometimes 2 seconds wasn't long enough, meaning the transaction was not available yet. This is fixed by polling for transaction details every 0.5 seconds until it is available.
