### ISSUE TITLE
Improved support for date/time

### ISSUE THREAD

**Issue by rkalis** [Bitcoin-com/cashscript#30]
Currently time checks can be done with either a blockheight (default) or a timestamp. However, we could add support for date/time objects or literals that are converted to timestamps in the background. This would allow you to do something like:

```
int timestamp = `2019-08-01T18:12:00` + 7 days;
```

**Comment by nathanielCherian** [comment]
Hey, @rkalis, the issue is a bit old but I agree this feature would be very convenient and increase readability/error-catching. I created a new date literal that can be invoked with `date("2019-08-01T18:12:00")` and returns an `intLiteral` timestamp when parsed. The date must be in ISO 8601 format  I am not very experienced with ANLTR so my code may be inefficient but I can edit if necessary 😄

**Comment by rkalis** [comment]
Awesome! Will take the conversation to that PR :)

**Comment by rkalis** [comment]
Still need to release the new version, but I'll close this issue now. Thanks for the great work @nathanielCherian :tada:
