### ISSUE TITLE
Find a sustainable solution to the BITBOX vacuum

### ISSUE THREAD

**Issue by rkalis** [Bitcoin-com/cashscript#65]
Since March BITBOX (that CashScript depends on) is no longer maintained. To fix this vacuum, CashScript now uses a combination of BITBOX, bitcoincashjs-lib, and Chris Troutner's forks of those. This is kind of confusing in the code as there is no one way to do things. So we should find a sustainable solution to this problem. The best maintained libraries are currently:

* Chris Troutner's bch-js. This is not TS and lacks some of the features that BITBOX has.
* bitcore-lib-cash. This has most of the functionality needed, but with a somewhat clunky API.
* libauth + electrum-cash. libauth still lacks some required functionality, but this would be the most lightweight solution.

I have good relations with Chris (bch-js), Jonathan (electrum-cash) and Jason (libauth), so I think any of those would be the way to go.

**Comment by nyusternie** [comment]
> Since March BITBOX (that CashScript depends on) is no longer maintained.

WTF?!? 🤬 Then why not post that shit in __BIG BRIGHT LETTERS__ on https://developer.bitcoin.com?? The API https://rest.bitcoin.com is also incredibly unstable. Had re-write A LOT of code recently, and in the process, migrated over to BitDB/BitSocket and Insomnia from __[Fountainhead](https://fountainhead.cash)__.

> I think the way to go is to migrate fully to bch-js some time in the future and work with Chris to make sure the library has all required features.

I actually haven't used `bch-js` personally, but Chris is a super dev (very consistent) in my book, so this makes the most sense.

> bitcore-lib-js. This has most of the functionality needed, but with a somewhat clunky API.

Did you mean `bitcore-lib-cash`? or do they both basically work the same? I'm currently using it with my own library __[NitoJS,](https://gitlab.com/bchplease/nitojs)__ still a WIP .. Plan is to build the APIs to match BITBOX functionality with BitDB/BitSocket support. Also will have built-in failovers for if/when an endpoint goes down (a MUST if you're doing anything on-chain).

**Comment by rkalis** [comment]
Yes I meant `bitcore-lib-cash` 😅. I've also been using @bitjson's `libauth` (previously `bitcoin-ts`), which is great as well, but doesn't have all the same features yet. I'll add NitoJS as well.

Currently I'm trying to cut down on the dependencies, and BITBOX is pretty heavyweight (and unfortunately so is BCH-JS). So what I'm considering to do is use `libauth` (0 dependencies) for all utility functions and @monsterbitar's `electrum-cash` for all network operations. That would drastically reduce the footprint of the library, which would be good.

**Comment by rkalis** [comment]
For good measure I wrote down a list of functionality requirements I have for a BCH library so I can use it in CashScript exclusively.

Requirements for utility library:
- Provide enum/object of all opcodes
- Compile Script between three formats (ASM, hex, list of opcodes and data)
- Minimally encode JS numbers to script numbers
- Decode script numbers to JS numbers
- hash160
- decode/encode P2SH input and output scripts
- Convert from output script to P2SH address or from redeem script to P2SH address
- Build a transaction
  - Add (partial) inputs
  - Add outputs (including OP_RETURN)
  - Setting sequence and encoding BIP68 (can also use [bip68](https://www.npmjs.com/package/bip68) separately)
  - Setting locktime
  - Generate sighash **preimage**
  - Transaction signing / general signing with Schnorr signatures

Requirements for network library:
- Get current block height
- Retrieve address' list of UTXOs (confirmed and unconfirmed)
- Retrieve address' balance (confirmed and unconfirmed) - can be derived from previous point
- Send raw transaction
- Retrieve transaction details

**Comment by nyusternie** [comment]
> So what I'm considering to do is use `libauth` (0 dependencies) for all utility functions and @monsterbitar's `electrum-cash` for all network operations.

wasn't familiar with `libauth`; will definitely check it out, as I'd also like to keep my library small; but fair warning, that's NOT the priority atm .. eventually (down the road), I'd like to modularize it into smaller parts, but right now I just need my shit to work (so size doesn't matter to me)..

@monsterbitar's `electrum-cash` is probably my favorite library right now .. I absolutely ❤️ the way the clustering works, and have started to mimic the functionality in NitoJS .. the only issue I have is that it depends on ElectrumX servers (using TCP), so it doesn't work via web browsers (at least not that I'm aware of), even though I see mention of web sockets in their [docs](https://electrumx.readthedocs.io/en/latest/changelog.html#version-1-12-0-13-may-2019).. 

__fwiw, I'm pretty committed to ONLY creating apps that can be run from an IPFS gateway__ 😉

> For good measure I wrote down a list of functionality requirements I have for a BCH library so I can use it in CashScript exclusively.

__nice!__ 👍

I'll be diving much deeper into CashScript over the next few weeks .. I'm currently modifying the Mecenas contract to work with a price Oracle (using the logic from your HodlVault example) .. it's the last piece before I can finally launch Causes Cash .. __I'll likely be hitting you up to review that contract in the next few days__ .. but also considering a Flipstarter to fund an "official" security audit w/ optimizations from Kalis Inc 😉

**Comment by bitjson** [comment]
Some links to get you started with Libauth:

> Provide enum/object of all opcodes

- [OpcodesBCH](https://libauth.org/enums/opcodesbch.html)
- [OpcodeDescriptionsBCH](https://github.com/bitauth/libauth/blob/d83b7572baa49dff8f31b0e52ff37da60ab364fd/src/lib/vm/instruction-sets/bch/bch-descriptions.ts#L21)
- [bitcoinABCOpcodes](https://github.com/bitauth/libauth/blob/d83b7572baa49dff8f31b0e52ff37da60ab364fd/src/lib/vm/instruction-sets/bch/fixtures/bitcoin-abc/bitcoin-abc-utils.ts#L10) – the names used by ABC (removes some underscores and excludes the `OP_` prefix, e.g. `OP_PUSHDATA_1` is `PUSHDATA1`)


> Compile Script between three formats (ASM, hex, list of opcodes and data)

For hex <-> `Uint8Array` (try searching `binTo` in the docs to see a lot of the formatting utils):
- [hexToBin](https://libauth.org/globals.html#hextobin)
- [binToHex](https://libauth.org/globals.html#bintohex)

For Uint8Array <-> `ParsedAuthenticationInstructions` (can be malformed) -> `AuthenticationInstructions` (always valid):
- [parseBytecode](https://libauth.org/globals.html#parsebytecode) - try the generic for stronger typing, e.g. `parseBytecode<OpcodesBCH>(hexToBin(hex))`
- [serializeParsedAuthenticationInstructions](https://libauth.org/globals.html#serializeparsedauthenticationinstructions)
- [authenticationInstructionsAreMalformed](https://libauth.org/globals.html#authenticationinstructionsaremalformed) type guard
- [authenticationInstructionsAreNotMalformed](https://libauth.org/globals.html#authenticationinstructionsarenotmalformed) type guard
- [serializeAuthenticationInstructions](https://libauth.org/globals.html#serializeauthenticationinstructions) (only valid instructions)
- [stringify](https://libauth.org/globals.html#stringify) (basically a JSON.stringify which supports Uint8Array and BigInt)
- [strigifyTestVector](https://libauth.org/globals.html#stringifytestvector) this can save you a lot of time

For Uint8Array <-> ASM:
- [assembleBytecodeBCH](https://libauth.org/globals.html#assemblebytecodebch)
- [disassembleBytecodeBCH](https://libauth.org/globals.html#disassemblebytecodebch)
- maybe also useful: [disassembleParsedAuthenticationInstructions](https://libauth.org/globals.html#disassembleparsedauthenticationinstructions)

Also notable:
- [assembleBitcoinABCScript](https://github.com/bitauth/libauth/blob/d83b7572baa49dff8f31b0e52ff37da60ab364fd/src/lib/vm/instruction-sets/bch/fixtures/bitcoin-abc/bitcoin-abc-utils.ts#L20-L36) - Bitcoin ABC's lossy ASM format (can't encode all push operations), currently used by `script_tests.json`

> Minimally encode JS numbers to script numbers

`encodeDataPush(bigIntToScriptNumber(BigInt(num)))` or `encodeDataPush(bigIntToScriptNumber(parseBytesAsScriptNumber(nonMinimalNumber)))` (see the docs for `encodeDataPush`)

- [bigIntToScriptNumber](https://libauth.org/globals.html#biginttoscriptnumber)
- [encodeDataPush](https://libauth.org/globals.html#encodedatapush) - `Returns the minimal bytecode required to push the provided data to the stack. [...]`

> Decode script numbers to JS numbers

- [parseBytesAsScriptNumber](https://libauth.org/globals.html#parsebytesasscriptnumber) (this one has pretty extensive docs about Script Numbers in general, too)

And some related stuff:

- [booleanToScriptNumber](https://libauth.org/globals.html#booleantoscriptnumber)
- [padMinimallyEncodedScriptNumber](https://libauth.org/globals.html#padminimallyencodedscriptnumber)

> hash160

- [instantiateRipemd160](https://libauth.org/globals.html#instantiateripemd160)
- [instantiateSha256](https://libauth.org/globals.html#instantiatesha256)

> Convert from output script to P2SH address or from redeem script to P2SH address

- [cashAddressToLockingBytecode](https://libauth.org/globals.html#cashaddresstolockingbytecode)
- [lockingBytecodeToCashAddress](https://libauth.org/globals.html#lockingbytecodetocashaddress)
- [base58AddressToLockingBytecode](https://libauth.org/globals.html#base58addresstolockingbytecode)
- [lockingBytecodeToBase58Address](https://libauth.org/globals.html#lockingbytecodetobase58address)
- [addressContentsToLockingBytecode](https://libauth.org/globals.html#addresscontentstolockingbytecode)
- [lockingBytecodeToAddressContents](https://libauth.org/globals.html#lockingbytecodetoaddresscontents)

For transaction building and signing, I recommend you either wait to switch until the transaction generation APIs in Libauth are stable, or role your own (for simple cases like going to/from P2PKH, the Libauth transaction compiler probably isn't necessary 😅). 

For signing, note that Libauth [uses the term "signing serialization" rather than "sighash"](https://twitter.com/bitjson/status/1194292080585121794), so the method you'll need is [`generateSigningSerializationBCH`](generateSigningSerializationBCH).

And please be sure to open issues/PRs in the [Libauth repo](https://github.com/bitauth/libauth) if you come across confusing or incorrect docs!

**Comment by p0o** [comment]
If these changes happens is it gonna be backward compatible to Bitbox? considering that SignatureTemplate is using a Bitbox object, I assume it's possible to ducktype the object and support both the old and new way?

**Comment by rkalis** [comment]
That is a very good point @p0o! I think it should be possible to keep that same interface and allow you to input a bitbox ECPair. This is definitely something I'll keep in mind.

**Comment by rkalis** [comment]
This has been resolved. CashScript no longer has any dependency on BITBOX. It now uses Libauth for all utility functionality, and uses a `NetworkProvider` interface for network operations. NetworkProviders are available for electrum-cash, bch-js and bitbox, while electrum-cash is the default. Anyone else can implement a different network provider using a different library (or even for a different network, such as BTC 🤷‍♂️) if they want to.

Regarding @p0o's point, the CashScript SDK is now library-agnostic and can be combined with any library if needed. The first argument of `SignatureTemplate` used to be a bitbox `ECPair`, but can now be a bitbox or bchjs `ECpair`, a bitcore-lib-cash `PrivateKey` a WIF string or a raw private key buffer. As long as the library supports exporting a private key as WIF or raw buffer, it is compatible.
