### ISSUE TITLE
Could the Mecenas contract be drained by a rogue actor?

### ISSUE THREAD

**Issue by nyusternie** [Bitcoin-com/cashscript#66]
Greetings @rkalis,

I've finally started playing with CashScript; and I must say I'm loving it! Finally feels like I can start using some of my Solidity skills in the BCH community.

The first contract I'd like to get working is Mecenas.cash for the https://causes.cash platform. I've been having great success on my first go-round with the contract, however, there's an issue that I can't shake.

https://github.com/Bitcoin-com/cashscript/blob/d8b5c4d50366b3fa007ee7345b41ca1fe86d8593/examples/mecenas.cash#L20

The first half of the conditional for the `receive` function makes an "assumption" that the contract is below the pledge amount. There's even a pull that claims `The recipient must claim all of of it.` __But what if they DON'T claim all of it.__

It appears that the library enforces this by __"automatically"__ sending change back to the contract address when you attempt to send less than the pledge amount, even though the contract balance is greater; which triggers the __"else"__ and FAILS (as it should).

However, what if someone were to execute the contract without using the library and DOES NOT add the second output back to the contract. Would that not still trigger the first half of the conditional and __send the remaining UTXO balance to the miners as a fee,__ as there's no enforcement of a 2nd (remaining balance) output?? A rogue actor could literally send 0 value, using up all the contract's UTXOs. Maybe I'm missing something obvious, but I'm just concerned that __a "manually" crafted transaction could circumvent the contract's current protections.__

Anyway, I'm very excited to continue working with CashScript and looking forward to giving those Ethereum guys a run for their ΞTH one day 🙏

Cheers! 😉

**Comment by rkalis** [comment]
Hey @nyusternie! I think I should probably add some more comments to those example contracts, thanks for bringing that to my attention!

So basically there are two cases: one where the contract balance is higher than the pledge amount (+fee) and one where it is less than or equal to the pledge amount (+fee). This can be seen as the case where the remainder should be sent back to the contract and the case where all the balance should be sent to the recipient.

```solidity
// Balance is less than pledge + fee, so all the remaining balance
// should be sent to the recipient.
if (intValue <= pledge + fee) {
    // Subtract the miner fee from the UTXO balance (`intValue`) to get amount to send
    bytes8 amount1 = bytes8(intValue - fee);
    // Construct output object sending this amount to the recipient
    bytes34 out1 = new OutputP2PKH(amount1, recipient);
    // Check that the ONLY output in this transaction is the output constructed above
    require(hash256(out1) == tx.hashOutputs);
// Else: Balance is higher than pledge, so a pledge should be sent 
// to the recipient, and the rest back to the contract
} else {
    // amount one is the pledge amount
    bytes8 amount1 = bytes8(pledge);
    // amount two is the remainder
    bytes8 amount2 = bytes8(intValue - pledge - fee);
    // Construct output object that sends pledge amount to the recipient
    bytes34 out1 = new OutputP2PKH(amount1, recipient);
    // Construct output object that sends remainder back to the contract
    bytes32 out2 = new OutputP2SH(amount2, hash160(tx.bytecode));
    // Check that the ONLY outputs in this transaction are those constructed above
    require(hash256(out1 + out2) == tx.hashOutputs);
}
```

Let's make it concrete with an example, e.g. the pledge is 1M sats, and the balance is 2M sats, the recipient is Alice and the malicious actor is Craig.

**Regular use - else branch**
1. Alice uses the CashScript SDK and sends 1M sats from the contract to her address and specifies a fixed fee of 1K sats. 
2. The CashScript SDK automatically adds a "change" output back for the remaining 999K sats.
3. In the contract we hit the if-statement and go into the else block (because it calculates `2M > 1M + 1K`)
4. The contract then constructs 1 output of 1M to Alice and 1 output of 999K back to the contract.
5. The contract checks that these two outputs are the only outputs, which is correct, so the function succeeds.

**Regular case - if branch**
After executing the previous transaction, there is 999K left in the contract.
1. Alice needs to do some calculation on her end to know how much she can send, so she retrieves the contract balance and sees its 999K, then subtracts the fixed 1K fee.
2. Alice uses the CashScript SDK and sends 998K sats from the contract to her address and specifies a fixed fee of 1K sats. 
3. The CashScript SDK does **not** add a "change" output because there is no money left.
4. In the contract we hit the if-statement and go into the if block (because it calculates `999K <= 1M + 1K`).
5. The contract then constructs only 1 output of 998K to Alice (999K - 1K fee).
6. The contract checks that this output is the only one, which is correct, so the function succeeds.

**Proposed attack**
The balance of the contract is 2M again.
1. Craig constructs a transaction outside the CashScript SDK, sending 1M sats to Alice, but without a second "change" output back to the contract.
2. In the contract we hit the if-statement and go into the else block (because it calculates `2M > 1M + 1K`).
3. The contract then constructs 1 output of 1M to Alice and 1 output of 999K back to the contract.
4. The contract checks that these two outputs are the only outputs, which is not correct, because the change output is missing, so the function fails.

---

Perhaps it is confusing that `tx.value` in CashScript means the *value of the UTXO being spent*. This is different than e.g. `msg.value` in Solidity. Because of this, for example in Mecenas, every individual UTXO is actually its own contract, and if there are two separate UTXOs, the function will be independently evaluated for both UTXOs.

Does this explain it enough? I'm very open to hearing about improvements I can make to the language itself, documentation or examples to make it more clear!

**Comment by nyusternie** [comment]
> Perhaps it is confusing that tx.value in CashScript means the value of the UTXO being spent. This is different than e.g. msg.value in Solidity.

__yes!__ I didn't realize that it was __PER UTXO__; wrongfully assumed `tx.value` to be the value of all inputs..

> Represents the value of current UTXO being spent. This can be used to enforce the full balance or a specific part of the contract's balance to be spent.

you even mention it __[here in the docs,](https://cashscript.org/docs/language/globals#txvalue)__ but I believe I found this after my claim.   
__excellent docs btw!!!__ 👏👍

> Because of this, for example in Mecenas, every individual UTXO is actually its own contract

yeah, I gotta wrap my head around that concept.. 

also, what I realize now is that __you don't even need to DEPLOY Script contracts,__ like you do with Ethereum, you just need to fund them with BCH .. that's so amazing!!

> Does this explain it enough?

yes. thank you 🙏  
appreciate you @rkalis, you're doing __BIG__ things for Bitcoin 😉
