### ISSUE TITLE
Use of `tx.locktime` in streaming contract?

### ISSUE THREAD

**Issue by nyusternie** [Bitcoin-com/cashscript#68]
https://github.com/Bitcoin-com/cashscript/blob/20630f3e6b68bc649dc38eeb326cba003db0c100/examples/mecenas_locktime.cash#L15

I "think" I understand the use of the `tx.locktime` in this contract, as a means to restrict the block height, by replacing this value during each execution .. although I don't really understand `nLockTime` very well..

So is that why you are using `tx.locktime` and NOT `tx.time`? As you said, __"But for safety it is recommended to use `tx.time` over `tx.locktime` in almost all cases."__

---

https://github.com/Bitcoin-com/cashscript/blob/20630f3e6b68bc649dc38eeb326cba003db0c100/examples/mecenas_locktime.cash#L17

In your new Covenant guide, this has been changed to
```
require(pledge % passedBlocks == 0);
```
which seems much cleaner to me, as I learned from __[Tobias Ruck's "Big Mul"](https://gitlab.com/GeneralProtocols/research/-/blob/master/bigmul/bigmul.ipynb)__..

---

> A drawback of using this "simulated state" method is that every new stream is a new contract with its own address.

ahh, I see.. so what you need is a UI/UX master to make this seemless?? huh, maybe I could handle that?? 🤔

---

fyi, https://cashscript.org/docs/language/examples is now giving 404

**Comment by rkalis** [comment]
> So is that why you are using tx.locktime and NOT tx.time? As you said, "But for safety it is recommended to use tx.time over tx.locktime in almost all cases."

So `tx.time` can **only** be used in the construction `tx.time >= x` and can be used *without* using covenants. `tx.locktime` can be used however you want, but you need to use covenants for it.

But be careful with `tx.locktime` any way, since checking something like `tx.locktime < x` doesn't really mean anything since `tx.locktime` **only** means that this is the **minimum** block number of the transaction, so if you check `tx.locktime < 100`, you're saying the minimum block number should be less than 100. But since it's the **minimum block number**, the **actual block number** can be much higher than 100, so the check is not really doing anything.

Because of that I recommend to use `tx.time` for basically all use cases, since that is much less error-prone. But in this case we want to apply some arithmetic to `tx.locktime` so we can apply new rules to the "next" stream.

> In your new Covenant guide, this has been changed to [...] which seems much cleaner to me

Yeah exactly, I don't know why I did the other thing earlier 😅 

> ahh, I see.. so what you need is a UI/UX master to make this seemless?? huh, maybe I could handle that?? 🤔

So yeah basically you would need a way to mitigate the fact that the "same" contract uses multiple different addresses. For example you could store the "latest" address in a databse or something. It's not set in stone how to best do this though. If you want to pick that up and see if you can figure something out that would be great! 💪 

> fyi, cashscript.org/docs/language/examples is now giving 404

Oh man I hate that this keeps happening. It's because of Docker caching D: I think I finally fixed it for good now though 🤞

**Comment by nyusternie** [comment]
> `tx.locktime` only means that this is the minimum block number of the transaction

huh, kinda a weird, I don't really get it, but I'll digest a bit and hit you back if I'm still unclear 🤔

https://github.com/Bitcoin-com/cashscript/blob/20630f3e6b68bc649dc38eeb326cba003db0c100/examples/mecenas_locktime.cash#L21

curious as to how you were able to change the above to:
```
bytes newContract = 0x04 + tx.locktime + tx.bytecode.split(5)[1];
```
what happened to the `OP_CODE PUSH`?

---

in regards to MY use-case, I'll have to think a bit if it's worth it to have to track a new `tx.locktime` contract each execution vs. just "being on point" with the execution based on `tx.time` .. i'm sure there are pros-and-cons, but hopefully I can get this all sorted out today .. gotta keep things movin' 😉

**Comment by nyusternie** [comment]
didn't mean to close it .. hit the wrong button 😣

**Comment by rkalis** [comment]
> huh, kinda a weird, I don't really get it, but I'll digest a bit and hit you back if I'm still unclear 🤔
I recommend [this article](https://prestwi.ch/bitcoin-time-locks/) (specifically the nLocktime section in this case) to get a better understanding of what the `nLocktime` field (`tx.locktime` in CashScript) means. I must have read that article like ten times when I was learning about locktimes haha.

> what happened to the OP_CODE PUSH?
Actually the old coded was wrong. If the data we're pushing is <76 bytes, we don't have to use a specific PUSHBYTES opcode (see https://en.bitcoin.it/wiki/Script)

**Comment by nyusternie** [comment]
> If the data we're pushing is <76 bytes, we don't have to use a specific PUSHBYTES opcode

got it!

and thanks for the article .. really appreciate all of your help 🙏

**Comment by rkalis** [comment]
Happy to help!

**Comment by nyusternie** [comment]
Don't mean to keep re-opening this issue, but I guess I have one last question before I can finalize my new contract. You basically answered it already.

> But be careful with tx.locktime any way, since checking something like tx.locktime < x doesn't really mean anything since tx.locktime only means that this is the minimum block number of the transaction, so if you check tx.locktime < 100, you're saying the minimum block number should be less than 100. But since it's the minimum block number, the actual block number can be much higher than 100, so the check is not really doing anything.

Is there any method via CashScript to __"expire" a Price Oracle's signature__ after a certain block height (obviously to prevent mal-pricing attacks). I'm certain now that it can't be done with `tx.time` given the limited construction; but I'd like to know if you have a method using `tx.locktime` and covenants?

I think my current contract is about 180 opcodes (after stripping out everything NOT critical), so I'd have limited space anyway, but I'd like to explore EVERY option before finalizing the contract and I start extensive testing.

My current (alternative) solution is to allow the Oracle's sig to front-run the contract with a head-start of 3 hours to prevent anyone else from using "expired" data when executing the contract (while still allowing an "open" fallback if the Oracle fails/disappears). The obvious problem is if the Oracle goes down for more than 3+ hours it loses its effectiveness (as anyone could then use ANY Oracle sig since contract creation), so it's not ideal, but I believe it'll get the job done for now..

**Comment by nyusternie** [comment]
> There‘s no expire field for transactions

sure! not for transactions, but how about for contracts?

`require(tx.time < maxBlockHeight)` OR `if (tx.locktime > maxBlockHeight) { return }` is what I would have expected to use, but both of these do not seem to work they way I would expect.

**Comment by nyusternie** [comment]
> The user is free to provide an earlier locktime value, but then they don't get the "full" payout (since passed blocks is calculated as `tx.locktime - intialBlock`).

that IS a very good incentive. I'll definitely consider this option.

> check in the contract code that `tx.locktime <= expiry`.

this is what I "initially" thought of when I read your locktime contract, however, you then made it clear that: 

> `tx.locktime < x` doesn't really mean anything since `tx.locktime` **only** means that this is the **minimum** block number of the transaction

so now, I'm a bit confused. how would the condition restrict on an `expiry` block, if it only considers it a __minimum__ block?

> What you then might get is people splitting up their payouts. [...] Which sounds good to me.

sounds good to me too. but I'm still not sure how that works .. let me experiment with `tx.locktime <= expiry` and I'll see if I can make better sense of it 😉

thanks @EyeOfPython and @rkalis for the valuable input .. I'd really like to get this done and implemented into Causes Cash asap 🙏

**Comment by rkalis** [comment]
So the reason why I think in this case you could use `tx.locktime <= expiry` is because we *incentivise* the user to set `tx.locktime` to the current block. Without that incentive the user can set the `tx.locktime` to a lower value than the current block, in which case `tx.locktime <= expiry` does not mean anything. 

But in the `mecenas_locktime` example, the user's payout is directly linked to setting the `tx.locktime` **as high as possible**. So it is **technically** still possible for someone to set a lower locktime, in which again `tx.locktime <= expiry` does not mean anything. But if they do that, then their contract payout is lower (and they still have to claim their funds for the higher `tx.locktime` at a later date), so they are incentivised **not to do that**.

Does that make any sense?

**Comment by nyusternie** [comment]
> So the reason why I think in this case you could use `tx.locktime <= expiry` is because we _incentivise_ the user to set `tx.locktime` to the current block.

Ahhh, got it!

> Does that make any sense?

yes! perfectly 👍

Okay, I believe I'm all set for now. I'll attempt to use `tx.locktime <= expiry`, to limit the validity of the price oracle's sigs, which means I've gotta re-write 1/2 my contract, but this is the right way to go. __Time to get to work!__ 🧐

Thank you as always 🙏
