### ISSUE TITLE
Possibility for RNG?

### ISSUE THREAD

**Issue by p0o** [Bitcoin-com/cashscript#84]
Is there any possibility for having something similar to RNG in Cash Script? I know that Bitcoin Script doesn't provide anything for that but I remember @eyeofpython had some ideas about using the merkle proof + verifying POW inside the script but I don't understand it very well.

I think having an example for a simple RNG provides great opportunities for betting and gaming contracts.

**Comment by rkalis** [comment]
Hey @p0o, I must have missed this issue earlier. 

Sounds interesting. I guess it should be possible to do some kind of merkle proof to get an input's block header and use the PoW as entropy for RNG. 

I know that in ETH it is not considered secure RNG to use the block header/hash as entropy, but I think it should be more secure on BCH as a single block represents a lot more work than on ETH (due to the 15s block time), and is therefore more difficult to manipulate.

I'm not entirely sure what the security implications are here, but I think it should be posible to create an example contract that does do a merkle proof for the `tx.outpoint` transaction and then use the PoW from that block as entropy to do some RNG. I'll ask @EyeOfPython for his thoughts about this as well.

**Comment by rkalis** [comment]
I looked into this in a bit more depth and it is definitely possible to do something like this, but to do a merkle proof of variable depth and up until the max block size for BCH, you'd need to either use some form of chained covenant contracts or a larger script limit. So for now I think the complexity is too high to add as an example to this repo, but we could revisit it at a later date if something changes.

**Comment by p0o** [comment]
Okay sure, thanks Rosco
