### ISSUE TITLE
Support for [CHIP-2021-02: Native Introspection Opcodes]

### ISSUE THREAD

**Issue by monsterbitar** [Bitcoin-com/cashscript#92]
Could we have a branch with support for the native introspection chip, to make it easier for people to test and evaluate when the testnet comes online?

List of opcodes: https://gitlab.com/GeneralProtocols/research/chips/-/blob/master/CHIP-2021-02-Add-Native-Introspection-Opcodes.md

**Comment by rkalis** [comment]
Cool! The new BCH Script features will go live on May 15th 2022, so that's still more than half a year away.

That said there's a test network already live with these new features so I plan to release a `cashscript@next` version some time in november for people that already want to try it out on testnet.

I'm not sure what that means for the VS Code extension, since ideally we'd want it to show the old autocompletions if you're not using the "beta" version, but the new ones if you *are* using it.

If that is impossible or difficult it's also fine to make the changes to the extension when the changes go live in the main version of CashScript in May.

**Comment by nathanielCherian** [comment]
Awesome, can't wait to try it out! I can work on a separate branch and publish the .vsix package so those who want autocompletion with ```cashscript@next``` can manually install it.

**Comment by rkalis** [comment]
That makes sense, awesome!

**Comment by rkalis** [comment]
This has been implemented in `v0.7.0-next.0`. If some issues with it come up I'll have the time to fix that before May, if no issues come up, I will release `v0.7.0` once the May 2022 upgrade hits mainnet.

**Comment by rkalis** [comment]
`v0.7.0` has been released for mainnet support of native introspection
